# Qwen
QWEN_API_KEY = "your-api-key-here"

MODEL_NAME = "qwen-plus"

# Treasury
INITIAL_TREASURY = 50000

# PID
PID_KP = 3000
PID_KI = 50
PID_KD = 500

# Market
MARKET_RANDOM_MIN = -0.05
MARKET_RANDOM_MAX = 0.05

BLACK_SWAN_PROBABILITY = 0.10

BLACK_SWAN_MIN = -0.10
BLACK_SWAN_MAX = -0.05

PRESSURE_MULTIPLIER = 0.20

PRESSURE_DECAY = 0.70